### ISSUE TITLE
In the QA setting, the "knowledge" part of the question is not being passed to the model

### ISSUE THREAD

**Issue by pminervini** [RUCAIBox/HaluEval#17]
Hi, I was going through [evaluate.py](https://github.com/RUCAIBox/HaluEval/blob/main/evaluation/evaluate.py) and it seems that, in the QA setting, the "knowledge" attribute of each instance is not being passed to the model jointly with the question: https://github.com/RUCAIBox/HaluEval/blob/main/evaluation/evaluate.py#L187

Is this intended?

**Comment by pminervini** [comment]
To me it seems like it should be included, no?

![Screenshot_2023-12-06-02-20-22-197_com.google.android.apps.docs.jpg](https://github.com/RUCAIBox/HaluEval/assets/227357/50caf12b-5de5-415f-8ed4-a668e119b517)

**Comment by Xiaoxue-xx** [comment]
Hi, evaluate.py is a basic evaluation script and does not include the evaluation method **Knowledge Retrieval**  in improvement strategies. Table 2 is the instruction of hallucination sampling instead of hallucination recognition. Table 13 presents the instruction of hallucination recognition.

**Comment by pminervini** [comment]
Oh I see, thanks!
